# -*- coding: utf-8 -*-
"""Dynamic Matching Markets: from when to whom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjoIFGTCI8PDHDRulKeyRuNEmCEp079w
"""

import numpy as np
from scipy.special import lambertw
from scipy.optimize import fsolve, brentq


def one_minus_exp_neg(z):
    """Stable computation of 1 - exp(-z)."""
    return -np.expm1(-z)


def one_minus_power(p, n):
    """Stable computation of 1 - (1 - p)^n for integer n >= 0."""
    if n <= 0:
        return 0.0
    return -np.expm1(n * np.log1p(-p))


def pi_H(x, y, d1):
    return one_minus_exp_neg(d1 * y / 2.0)

def pi_E(x, y, d1, d2):
    return one_minus_exp_neg((d1 * x + d2 * y) / 2.0)

def rho_EH(x, y, d1, d2):
    """
    Fluid-limit uniform-rule share assigned to H neighbors.

    In the ODE limit this is d1*x/(d1*x + d2*y). The finite-m CTMC
    simulation samples binomial neighbor counts directly.
    """
    denom = d1 * x + d2 * y
    return d1 * x / denom if denom > 0 else 0.0

def rho_EE(x, y, d1, d2):
    """
    Fluid-limit uniform-rule share assigned to E neighbors.

    In the ODE limit this is d2*y/(d1*x + d2*y). The finite-m CTMC
    simulation samples binomial neighbor counts directly.
    """
    denom = d1 * x + d2 * y
    return d2 * y / denom if denom > 0 else 0.0


def solve_fixed_point(func, starts, args=(), bounds=((0.0, 1.0), (0.0, 1.0)),
                      tol=1e-9, name="fixed point"):
    best = None

    for guess in starts:
        with np.errstate(over="ignore", invalid="ignore"):
            sol = fsolve(func, guess, args=args, full_output=True)
            point = np.asarray(sol[0], dtype=float)
            residual = np.linalg.norm(func(point, *args))
        ier = sol[2]
        message = sol[3]

        in_bounds = (
            bounds[0][0] <= point[0] <= bounds[0][1]
            and bounds[1][0] <= point[1] <= bounds[1][1]
        )

        if best is None or residual < best[0]:
            best = (residual, point, ier, message)

        if residual < tol and in_bounds:
            return float(point[0]), float(point[1])

    residual, point, ier, message = best
    raise RuntimeError(
        f"{name} not found. Best residual={residual:.3e}, "
        f"point={point}, ier={ier}, message={message}"
    )


# ----------------------------------------------------------------------------
# Greedy
# ----------------------------------------------------------------------------
def greedy_drift(state, d1, d2):
    x, y = state
    pH = pi_H(x, y, d1); pE = pi_E(x, y, d1, d2)
    rEH = pE * rho_EH(x, y, d1, d2); rEE = pE * rho_EE(x, y, d1, d2)
    return [0.5 * (1 - pH) - x - 0.5 * rEH,
            0.5 * (1 - pE) - y - 0.5 * pH - 0.5 * rEE]

def greedy_fixed_point(d1, d2):
    starts = [(max(0.05, min(0.45, 1.0/np.sqrt(1+d1))), max(1e-6, 1.0/d2))]
    starts += [(x0, y0) for x0 in [0.1, 0.2, 0.3, 0.4]
                       for y0 in [1e-3, 1e-2, 0.05]]
    return solve_fixed_point(
        greedy_drift,
        starts,
        args=(d1, d2),
        bounds=((0.0, 1.0), (0.0, 1.0)),
        name=f"Greedy fixed point at d1={d1}, d2={d2}",
    )

def L_greedy(d1, d2):
    x, y = greedy_fixed_point(d1, d2)
    return x + y


def L_greedy_closed_form_d2_inf(d1):
    """
    Greedy as d2 -> infinity.

    x solves:
        log(x) + d1*x*(1-x)/(2*(1-2*x)) = 0
    on (0, 1/2).
    """
    def scalar_eq(x):
        return np.log(x) + d1 * x * (1.0 - x) / (2.0 * (1.0 - 2.0 * x))

    return brentq(scalar_eq, 1e-15, 0.5 - 1e-12)


def greedy_correction_coeff_d2(d1):
    """
    Coefficient C^Greedy(d1) in

        L_G(d1, d2) = L_G(d1, infinity) + C^Greedy(d1)/d2 + O(d2^-2).

    Uses the corrected first-order expansion of the Greedy fixed-point equations.
    """
    x0 = L_greedy_closed_form_d2_inf(d1)
    c0 = d1 * x0**2 / (1.0 - 2.0 * x0)
    D0 = d1 * x0 + c0

    f_D = c0 * ((x0 / 2.0) * D0 - (1.0 - x0)) / D0**2
    f_z = (1.0 - x0) / D0

    A = np.array([
        [1.0 + d1 * x0 / 2.0, x0 / 2.0],
        [1.0 - d1 * f_D, -(f_D + f_z)],
    ])
    rhs = np.array([
        -c0 * (1.0 + d1 / 2.0),
        c0,
    ])

    a, _ = np.linalg.solve(A, rhs)
    return a + c0


# ----------------------------------------------------------------------------
# Type-Aware Greedy
# ----------------------------------------------------------------------------
def TAG_drift(state, d1, d2):
    x, y = state
    tilde_rEH = one_minus_exp_neg(d1 * x / 2.0)
    tilde_rEE = np.exp(-d1 * x / 2.0) * one_minus_exp_neg(d2 * y / 2.0)
    return [0.5 * np.exp(-d1 * y / 2.0) - x - 0.5 * tilde_rEH,
            (0.5 * np.exp(-(d1 * x + d2 * y) / 2.0) - y
             - 0.5 * one_minus_exp_neg(d1 * y / 2.0)
             - 0.5 * tilde_rEE)]

def TAG_fixed_point(d1, d2):
    starts = [(max(0.05, min(0.45, 1.0/np.sqrt(1+d1))), max(1e-6, 1.0/d2))]
    starts += [(x0, y0) for x0 in [0.1, 0.2, 0.3, 0.4]
                       for y0 in [1e-3, 1e-2, 0.05]]
    return solve_fixed_point(
        TAG_drift,
        starts,
        args=(d1, d2),
        bounds=((0.0, 1.0), (0.0, 1.0)),
        name=f"TA-Greedy fixed point at d1={d1}, d2={d2}",
    )

def L_TAG(d1, d2):
    x, y = TAG_fixed_point(d1, d2)
    return x + y

def L_TAG_closed_form_d2_inf(d1):
    """TA-Greedy as d2 -> infty: x = 2 W(d1/4) / d1 (Lemma 8)."""
    return float(2.0 * np.real(lambertw(d1 / 4.0)) / d1)


def TAG_correction_coeff_d2(d1):
    """
    Coefficient C^TA-Greedy(d1) in

        L_TAG(d1, d2) = L_TAG(d1, infinity) + C^TA-Greedy(d1)/d2 + O(d2^-2).
    """
    x0 = L_TAG_closed_form_d2_inf(d1)
    c0 = 2.0 * np.log(2.0)

    a = -d1 * c0 / (2.0 * (2.0 + d1 * x0))
    return a + c0


# ----------------------------------------------------------------------------
# Patient
# ----------------------------------------------------------------------------
def patient_drift(state, d1, d2):
    x, y = state
    pH = pi_H(x, y, d1); pE = pi_E(x, y, d1, d2)
    rEH = pE * rho_EH(x, y, d1, d2); rEE = pE * rho_EE(x, y, d1, d2)
    return [0.5 - x - y * rEH,
            0.5 - x * pH - y * (1.0 + rEE)]

def patient_fixed_point(d1, d2):
    starts = [(0.45, max(1e-3, 1.0/max(d1, 1.0)))]
    starts += [(x0, y0) for x0 in [0.4, 0.45, 0.49]
                       for y0 in [0.01, 0.05, 0.1, 0.2]]
    return solve_fixed_point(
        patient_drift,
        starts,
        args=(d1, d2),
        bounds=((0.0, 1.0), (0.0, 1.0)),
        name=f"Patient fixed point at d1={d1}, d2={d2}",
    )

def L_patient(d1, d2):
    x, y = patient_fixed_point(d1, d2)
    return 2 * (x + y) - 1.0  # aggregate balance

def L_patient_closed_form_d2_inf(d1):
    """Patient as d2 -> infty: y* = 2 W(d1/8)/d1, L = 2 y* (Lemma 10)."""
    y_star = 2.0 * np.real(lambertw(d1 / 8.0)) / d1
    return 2.0 * y_star

def L_patient_correction_d2(d1, d2):
    """Patient with 1/d2 closed-form correction (Lemma 11)."""
    y_star = 2.0 * np.real(lambertw(d1 / 8.0)) / d1
    return 2.0 * y_star + (-d1 * y_star * (d1 + 4) / ((2 + d1 * y_star) * d2))


# ----------------------------------------------------------------------------
# Type-Aware Patient
# ----------------------------------------------------------------------------
def TAP_drift(state, d1, d2):
    x, y = state
    tilde_rEH = one_minus_exp_neg(d1 * x / 2.0)
    tilde_rEE = np.exp(-d1 * x / 2.0) * one_minus_exp_neg(d2 * y / 2.0)
    return [0.5 - x - y * tilde_rEH,
            0.5 - x * pi_H(x, y, d1) - y * (1.0 + tilde_rEE)]

def TAP_fixed_point(d1, d2):
    starts = [(0.25, 0.25)]
    starts += [(x0, y0) for x0 in np.linspace(0.05, 0.49, 7)
                       for y0 in np.linspace(0.05, 0.49, 7)]
    roots = TAP_all_fixed_points(d1, d2)
    if len(roots) > 1:
        print(f"WARNING: found {len(roots)} TA-Patient roots at d1={d1}, d2={d2}: {roots}")
        return roots[0]
    if len(roots) == 1:
        return roots[0]
    return solve_fixed_point(
        TAP_drift,
        starts,
        args=(d1, d2),
        bounds=((0.0, 0.5), (0.0, 0.5)),
        name=f"TA-Patient fixed point at d1={d1}, d2={d2}",
    )


def unique_points(points, tol=1e-6):
    unique = []
    for p in points:
        if not any(np.linalg.norm(np.asarray(p) - np.asarray(q)) < tol for q in unique):
            unique.append(p)
    return unique


def TAP_all_fixed_points(d1, d2):
    starts = [(x0, y0) for x0 in np.linspace(0.02, 0.49, 12)
                       for y0 in np.linspace(0.02, 0.49, 12)]
    roots = []

    for guess in starts:
        with np.errstate(over="ignore", invalid="ignore"):
            sol = fsolve(TAP_drift, guess, args=(d1, d2), full_output=True)
            x, y = sol[0]
            residual = np.linalg.norm(TAP_drift([x, y], d1, d2))

        if residual < 1e-8 and 0 < x < 0.5 and 0 < y < 0.5:
            roots.append((float(x), float(y)))

    return unique_points(roots)

def L_TAP(d1, d2):
    x, y = TAP_fixed_point(d1, d2)
    return 2 * (x + y) - 1.0


def TAP_drift_d2_inf(state, d1):
    x, y = state
    tilde_rEH = one_minus_exp_neg(d1 * x / 2.0)
    tilde_rEE = np.exp(-d1 * x / 2.0)
    return [
        0.5 - x - y * tilde_rEH,
        0.5 - x * pi_H(x, y, d1) - y * (1.0 + tilde_rEE),
    ]


def TAP_fixed_point_d2_inf(d1):
    starts = [(0.25, 0.25)]
    starts += [(x0, y0) for x0 in np.linspace(0.05, 0.49, 7)
                       for y0 in np.linspace(0.05, 0.49, 7)]

    roots = TAP_all_fixed_points_d2_inf(d1)
    if len(roots) > 1:
        print(f"WARNING: found {len(roots)} TA-Patient d2=inf roots at d1={d1}: {roots}")
        return roots[0]
    if len(roots) == 1:
        return roots[0]

    return solve_fixed_point(
        TAP_drift_d2_inf,
        starts,
        args=(d1,),
        bounds=((0.0, 0.5), (0.0, 0.5)),
        name=f"TA-Patient d2=inf fixed point at d1={d1}",
    )


def TAP_all_fixed_points_d2_inf(d1):
    starts = [(x0, y0) for x0 in np.linspace(0.02, 0.49, 12)
                       for y0 in np.linspace(0.02, 0.49, 12)]
    roots = []

    for guess in starts:
        with np.errstate(over="ignore", invalid="ignore"):
            sol = fsolve(TAP_drift_d2_inf, guess, args=(d1,), full_output=True)
            x, y = sol[0]
            residual = np.linalg.norm(TAP_drift_d2_inf([x, y], d1))

        if residual < 1e-8 and 0 < x < 0.5 and 0 < y < 0.5:
            roots.append((float(x), float(y)))

    return unique_points(roots)


def L_TAP_d2_inf(d1):
    x, y = TAP_fixed_point_d2_inf(d1)
    return 2.0 * (x + y) - 1.0


def simulate(m, d1, d2, policy, T_burn=20.0, T_horizon=200.0, seed=None):
    """
    Event-driven CTMC simulation.

    Args:
      m         : market size (arrival rate per type is m/2)
      d1, d2    : compatibility densities
      policy    : 'greedy' | 'TAG' | 'patient' | 'TAP'
      T_burn    : burn-in time before counting begins
      T_horizon : total simulated time
    Returns:
      (L_total, L_H, L_E): empirical fractions perished unmatched.
    """
    assert policy in ('greedy', 'TAG', 'patient', 'TAP')
    rng = np.random.default_rng(seed)
    p_HE = d1 / (2.0 * m); p_EE = d2 / (2.0 * m)
    if not (0.0 <= p_HE <= 1.0 and 0.0 <= p_EE <= 1.0):
        raise ValueError(
            f"Invalid probabilities: p_HE={p_HE}, p_EE={p_EE}. "
            "Need d1/(2m) and d2/(2m) in [0, 1]."
        )
    rate_arr = m / 2.0  # per type

    H_pool = E_pool = 0
    t = 0.0
    arr_H = arr_E = perish_H = perish_E = 0
    counting = False

    while t < T_horizon:
        rate_total = 2 * rate_arr + (H_pool + E_pool)
        t += rng.exponential(1.0 / rate_total)
        if t >= T_horizon:
            break
        if not counting and t >= T_burn:
            counting = True
            arr_H = arr_E = perish_H = perish_E = 0

        u = rng.random() * rate_total
        if u < rate_arr:
            # H arrival
            if counting: arr_H += 1
            if policy in ('greedy', 'TAG') and E_pool > 0:
                if rng.random() < one_minus_power(p_HE, E_pool):
                    E_pool -= 1
                else:
                    H_pool += 1
            else:
                H_pool += 1
        elif u < 2 * rate_arr:
            # E arrival
            if counting: arr_E += 1
            if policy == 'greedy' and (H_pool > 0 or E_pool > 0):
                n_H = rng.binomial(H_pool, p_HE)
                n_E = rng.binomial(E_pool, p_EE)
                if n_H + n_E > 0:
                    if rng.random() < n_H / (n_H + n_E):
                        H_pool -= 1
                    else:
                        E_pool -= 1
                else:
                    E_pool += 1
            elif policy == 'TAG' and (H_pool > 0 or E_pool > 0):
                n_H = rng.binomial(H_pool, p_HE)
                if n_H > 0:
                    H_pool -= 1
                else:
                    n_E = rng.binomial(E_pool, p_EE)
                    if n_E > 0:
                        E_pool -= 1
                    else:
                        E_pool += 1
            else:
                E_pool += 1
        else:
            # Criticality event
            u2 = u - 2 * rate_arr
            if u2 < H_pool:
                # H critical
                if policy in ('greedy', 'TAG'):
                    H_pool -= 1
                    if counting: perish_H += 1
                else:  # Patient: try to match an E
                    if E_pool > 0 and rng.random() < one_minus_power(p_HE, E_pool):
                        H_pool -= 1; E_pool -= 1
                    else:
                        H_pool -= 1
                        if counting: perish_H += 1
            else:
                # E critical
                if policy in ('greedy', 'TAG'):
                    E_pool -= 1
                    if counting: perish_E += 1
                elif policy == 'patient':
                    n_H = rng.binomial(H_pool, p_HE)
                    n_E = rng.binomial(E_pool - 1, p_EE)
                    if n_H + n_E > 0:
                        if rng.random() < n_H / (n_H + n_E):
                            H_pool -= 1; E_pool -= 1
                        else:
                            E_pool -= 2
                    else:
                        E_pool -= 1
                        if counting: perish_E += 1
                else:  # TAP
                    n_H = rng.binomial(H_pool, p_HE)
                    if n_H > 0:
                        H_pool -= 1; E_pool -= 1
                    else:
                        n_E = rng.binomial(E_pool - 1, p_EE)
                        if n_E > 0:
                            E_pool -= 2
                        else:
                            E_pool -= 1
                            if counting: perish_E += 1

    return ((perish_H + perish_E) / max(1, arr_H + arr_E),
            perish_H / max(1, arr_H),
            perish_E / max(1, arr_E))


def average_simulations(m, d1, d2, policy, n_runs=4,
                         T_burn=20.0, T_horizon=200.0, base_seed=0):
    losses = [simulate(m, d1, d2, policy, T_burn, T_horizon, base_seed + k)[0]
              for k in range(n_runs)]
    return np.mean(losses), np.std(losses)


def run_sanity_checks():
    print("Fixed-point residuals (should all be < 1e-8):")
    for d1 in [1, 5, 10]:
        for d2 in [50, 500]:
            x_g, y_g = greedy_fixed_point(d1, d2)
            x_p, y_p = patient_fixed_point(d1, d2)
            r_g = np.linalg.norm(greedy_drift([x_g, y_g], d1, d2))
            r_p = np.linalg.norm(patient_drift([x_p, y_p], d1, d2))
            print(
                f"  d1={d1:>2}, d2={d2:>3}: "
                f"|F_Greedy|={r_g:.2e}  |F_Patient|={r_p:.2e}"
            )


def run_tables():
    print("\n" + "=" * 78)
    print("d2 = infinity limiting table")
    print("=" * 78)
    print(f"{'d1':>6} {'L^Greedy':>12} {'L^TAG':>12} {'L^Patient':>12} {'L^TAP':>12}")
    for d1 in [0.5, 1, 2, 5, 10, 50, 100]:
        Lg = L_greedy_closed_form_d2_inf(d1)
        Ltg = L_TAG_closed_form_d2_inf(d1)
        Lp = L_patient_closed_form_d2_inf(d1)
        Ltp = L_TAP_d2_inf(d1)
        fmt = lambda x: f"{x:.1e}" if abs(x) < 1e-3 else f"{x:.3f}"
        print(f"{d1:>6} {fmt(Lg):>12} {fmt(Ltg):>12} {fmt(Lp):>12} {fmt(Ltp):>12}")

    print("\n" + "=" * 78)
    print("Joint finite-(d1, d2) fixed-point table")
    print("=" * 78)
    d2_grid = [10, 50, 100, 500, np.inf]
    fns = {
        "Greedy": (L_greedy, L_greedy_closed_form_d2_inf),
        "TA-Greedy": (L_TAG, L_TAG_closed_form_d2_inf),
        "Patient": (L_patient, L_patient_closed_form_d2_inf),
        "TA-Patient": (L_TAP, L_TAP_d2_inf),
    }
    rows = [
        ("Greedy", 1), ("Greedy", 5), ("Greedy", 10),
        ("TA-Greedy", 1), ("TA-Greedy", 5),
        ("Patient", 1), ("Patient", 5),
        ("TA-Patient", 1), ("TA-Patient", 5),
    ]
    print(f"{'policy':>12} {'d1':>6} " + " ".join(f"{d2:>10}" for d2 in d2_grid))
    for policy, d1 in rows:
        finite_fn, inf_fn = fns[policy]
        values = [inf_fn(d1) if np.isinf(d2) else finite_fn(d1, d2) for d2 in d2_grid]
        print(f"{policy:>12} {d1:>6} " + " ".join(f"{v:>10.4f}" for v in values))

    print("\n" + "=" * 78)
    print("Greedy-vs-Patient crossover scan at d1 = 1")
    print("=" * 78)
    print(f"{'d2':>6} {'L^Greedy':>12} {'L^Patient':>12} {'winner':>8}")
    for d2 in [5, 10, 20, 30, 50, 70, 100, 200, 500]:
        Lg = L_greedy(1.0, d2)
        Lp = L_patient(1.0, d2)
        winner = "P" if Lp < Lg else "G"
        print(f"{d2:>6} {Lg:>12.4f} {Lp:>12.4f} {winner:>8}")


def run_correction_tables():
    print("\nGreedy and TA-Greedy 1/d2 correction coefficients")
    print(f"{'d1':>6} {'C^Greedy':>14} {'C^TA-Greedy':>16}")
    for d1 in [0.5, 1, 2, 5, 10, 50]:
        print(
            f"{d1:>6} "
            f"{greedy_correction_coeff_d2(d1):>14.4f} "
            f"{TAG_correction_coeff_d2(d1):>16.4f}"
        )


def run_simulation_checks():
    print("\n" + "=" * 78)
    print("CTMC simulation vs ODE prediction (m=5000 and 10000, n_runs=3)")
    print("=" * 78)
    print("  ODE fixed-point losses should be close to empirical CTMC long-run loss.")
    print("  Simulation error depends on m, horizon length, burn-in, autocorrelation, and n_runs.\n")
    print(f"{'m':>6} {'d1':>4} {'d2':>4} {'policy':>8} {'L_ODE':>10} {'L_CTMC':>22} {'gap':>10}")
    test_cases = [
        (1, 50,  'greedy'),  (1, 50,  'patient'),
        (1, 50,  'TAG'),     (1, 50,  'TAP'),
        (5, 100, 'greedy'),  (5, 100, 'patient'),
        (5, 100, 'TAG'),     (5, 100, 'TAP'),
    ]
    fns_full = {'greedy': L_greedy, 'TAG': L_TAG,
                'patient': L_patient, 'TAP': L_TAP}
    for m in [5000, 10000]:
        for d1, d2, pol in test_cases:
            Lo = fns_full[pol](d1, d2)
            Le, Ls = average_simulations(m, d1, d2, pol, n_runs=3,
                                          T_burn=10.0, T_horizon=80.0, base_seed=2024 + m)
            print(f"{m:>6} {d1:>4} {d2:>4} {pol:>8} {Lo:>10.4f} "
                  f"{Le:>10.4f} +/- {Ls:>6.4f}     {abs(Lo-Le):.4f}")


if __name__ == "__main__":
    run_sanity_checks()
    run_tables()
    run_correction_tables()
    run_simulation_checks()
